server:
  port: 2002

spring:
  application:
    name: consumer-2002
  rabbitmq:
    host: 192.168.1.20
    port: 5672
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/