server:
  port: 3001

spring:
  application:
    name: conf-server-3001
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quguanwen/Mylife/

#需要把配置中心注册到eureka中
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/